# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "0i725n165zn0jqi75rlm1ac8lpbjs20skbi7db31qbx2fsr1gix6";
    sha256bin64 = "1djyk1fzc4gvj2gsvvgyrzwf1mcv1z2n1krxjipj5dxarz6qkjxd";
    version = "79.0.3945.45";
  };
  dev = {
    sha256 = "1l6dsv9cv5gqd682mkawwd15x82f0m6rmnb0mig0lv84p89zpxz2";
    sha256bin64 = "1kbd000friz68fbgkrkgsdhcx17l4ar2s1bfzr34ckab2785g5ni";
    version = "80.0.3970.5";
  };
  stable = {
    sha256 = "03jvfz68nvmmrplygf96sh0l347p4h03c8vpw8yrglh6ycwkiigr";
    sha256bin64 = "1knsrdh4vj1zl3v1frzrvzg0pwb64zhq2il7pwskrfcbmsj3gkh6";
    version = "78.0.3904.108";
  };
}
